nav_wp:
  ros__parameters:
    waypoints: ["wp8", "wp3", "wp7", "wp6", "wp1", wp3", "wp4", "wp5", "wp2"]
    wp0: [0.0, 3.0]
    wp1: [1.0, 1.0]
    wp8: [-2.78, 3.38]
    wp3: [-1.0, -1.0]
    wp2: [-1.46, 1.06]
    wp4: [-3.0, -0.6]
    wp5: [0.1, 3.6]
    wp6: [0.105, -1.5]
    wp7: [-0.027, 1.87]